"use client";

import Link from "next/link";
import { ArrowRight, Check, Sparkles } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { Button } from "../../components/ui/button";

export default function LoginPage() {
  const router = useRouter(); const [email, setEmail] = useState("");
  return <main className="grid min-h-screen bg-[#09090b] lg:grid-cols-2"><section className="hidden flex-col justify-between border-r border-slate-800 bg-[radial-gradient(ellipse_at_top_left,_var(--tw-gradient-stops))] from-violet-900/45 via-[#11111a] to-[#09090b] p-12 lg:flex"><div className="flex items-center gap-2 text-lg font-semibold"><span className="grid h-8 w-8 place-items-center rounded-xl bg-violet-500"><Sparkles size={16} /></span>InternAgent</div><div><p className="text-sm font-semibold uppercase tracking-[0.22em] text-violet-300">Opportunity, thoughtfully managed</p><h1 className="mt-5 max-w-xl text-5xl font-semibold leading-[1.08] tracking-tight text-white">A calmer way to find the internship that fits.</h1><ul className="mt-10 space-y-4 text-sm text-slate-300">{["Discover roles matched to your preferences", "Prepare tailored materials from real experience", "Stay in control of every application"].map(item => <li key={item} className="flex items-center gap-3"><span className="grid h-5 w-5 place-items-center rounded-full bg-violet-500/20 text-violet-300"><Check size={12} /></span>{item}</li>)}</ul></div><p className="text-xs text-slate-600">Built around your decisions, not automation shortcuts.</p></section><section className="mx-auto flex w-full max-w-md flex-col justify-center px-6 py-12"><Link href="/" className="mb-14 flex items-center gap-2 text-lg font-semibold lg:hidden"><span className="grid h-8 w-8 place-items-center rounded-xl bg-violet-500"><Sparkles size={16} /></span>InternAgent</Link><p className="text-sm font-medium text-violet-300">Welcome back</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-white">Sign in to InternAgent</h2><p className="mt-3 text-sm leading-6 text-slate-400">Use your email to continue to your internship workspace.</p><form className="mt-8 space-y-5" onSubmit={event => { event.preventDefault(); router.push("/dashboard"); }}><label className="block text-sm font-medium text-slate-300">Email address<input value={email} onChange={event => setEmail(event.target.value)} type="email" required placeholder="you@example.com" className="mt-2 h-11 w-full rounded-xl border border-slate-700 bg-slate-900 px-3 text-white outline-none transition focus:border-violet-400" /></label><Button type="submit" className="w-full">Continue <ArrowRight size={16} /></Button></form><div className="my-6 flex items-center gap-3 text-xs text-slate-600"><span className="h-px flex-1 bg-slate-800" />or<span className="h-px flex-1 bg-slate-800" /></div><Button variant="outline" className="w-full">Continue with Google</Button><p className="mt-8 text-center text-xs leading-5 text-slate-600">By continuing, you agree to use InternAgent only with permitted job sources and authorized integrations.</p><p className="mt-5 text-center text-sm text-slate-400">New here? <Link className="text-violet-300 hover:text-violet-200" href="/onboarding">Set up your search</Link></p></section></main>;
}
