"use client";

import { ArrowLeft, ArrowRight, Check, CircleAlert, FileUp, Plus, ShieldCheck, Sparkles, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { type ChangeEvent, type ReactNode, useState } from "react";
import { Badge } from "../../components/ui/badge";
import { Button } from "../../components/ui/button";
import type { ApplicationMode } from "../../lib/types";
import { cn } from "../../lib/utils";

const roles = ["Software Engineering Intern", "Frontend Developer Intern", "Backend Developer Intern", "Full Stack Developer Intern", "AI/ML Intern", "Data Science Intern", "Data Analyst Intern", "Product Management Intern", "Cybersecurity Intern", "UI/UX Intern"];
const skills = ["Python", "Java", "C++", "JavaScript", "TypeScript", "React", "Next.js", "Node.js", "Express", "MongoDB", "PostgreSQL", "SQL", "AWS", "Docker", "Machine Learning", "PyTorch", "TensorFlow"];
const steps = ["Role", "Skills", "Location", "Duration", "Compensation", "Availability", "Preferences", "Resume", "Application mode"];

function OptionChip({ label, selected, onClick }: { label: string; selected: boolean; onClick: () => void }) { return <button onClick={onClick} className={cn("rounded-xl border px-3 py-2 text-sm transition", selected ? "border-violet-400 bg-violet-500/15 text-violet-100" : "border-slate-700 bg-slate-900/50 text-slate-400 hover:border-slate-600 hover:text-slate-200")}>{selected ? <Check className="mr-1.5 inline" size={14} /> : null}{label}</button>; }
function TextInput({ label, value, onChange, placeholder, type = "text", suffix }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; type?: string; suffix?: ReactNode }) { return <label className="block text-sm font-medium text-slate-300">{label}<span className="relative mt-2 block"><input type={type} value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder} className="h-11 w-full rounded-xl border border-slate-700 bg-slate-900 px-3 pr-20 text-sm text-white outline-none transition placeholder:text-slate-600 focus:border-violet-400" />{suffix ? <span className="absolute right-3 top-3 text-xs text-slate-500">{suffix}</span> : null}</span></label>; }
function Toggle({ label, detail, checked, onChange }: { label: string; detail?: string; checked: boolean; onChange: () => void }) { return <button className="flex w-full items-center justify-between gap-5 rounded-xl border border-slate-800 bg-slate-900/40 p-4 text-left transition hover:border-slate-700" onClick={onChange}><span><span className="block text-sm font-medium text-slate-200">{label}</span>{detail ? <span className="mt-1 block text-xs leading-5 text-slate-500">{detail}</span> : null}</span><span className={cn("relative h-6 w-11 shrink-0 rounded-full transition", checked ? "bg-violet-500" : "bg-slate-700")}><span className={cn("absolute top-1 h-4 w-4 rounded-full bg-white transition", checked ? "left-6" : "left-1")} /></span></button>; }

export default function OnboardingPage() {
  const router = useRouter(); const [step, setStep] = useState(0); const [selectedRoles, setSelectedRoles] = useState<string[]>([]); const [selectedSkills, setSelectedSkills] = useState<string[]>([]); const [roleInput, setRoleInput] = useState(""); const [skillInput, setSkillInput] = useState("");
  const [countries, setCountries] = useState(""); const [cities, setCities] = useState(""); const [workModes, setWorkModes] = useState({ remote: true, hybrid: true, onsite: false, relocate: false }); const [duration, setDuration] = useState({ min: "8", max: "16", unit: "weeks" });
  const [compensation, setCompensation] = useState({ minimum: "", currency: "USD", cadence: "monthly", unpaid: false }); const [availability, setAvailability] = useState({ earliest: "", latest: "" }); const [preferences, setPreferences] = useState({ industries: "", companies: "", excludedCompanies: "", keywords: "", maximum: "5" }); const [resumeName, setResumeName] = useState(""); const [resumeError, setResumeError] = useState(""); const [applicationMode, setApplicationMode] = useState<ApplicationMode>("review");
  const toggle = (list: string[], setList: (value: string[]) => void, item: string) => setList(list.includes(item) ? list.filter(value => value !== item) : [...list, item]);
  const addRole = () => { const value = roleInput.trim(); if (value && !selectedRoles.includes(value)) setSelectedRoles([...selectedRoles, value]); setRoleInput(""); };
  const addSkill = () => { const value = skillInput.trim(); if (value && !selectedSkills.includes(value)) setSelectedSkills([...selectedSkills, value]); setSkillInput(""); };
  const selectResume = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; setResumeError(""); if (!file) return; const extension = file.name.split(".").pop()?.toLowerCase(); if (!['pdf', 'docx'].includes(extension ?? "")) { setResumeError("Please select a PDF or DOCX file."); return; } if (file.size > 5 * 1024 * 1024) { setResumeError("Your resume must be 5 MB or smaller."); return; } setResumeName(file.name); };
  const next = () => { if (step === steps.length - 1) router.push("/dashboard"); else setStep(value => value + 1); };
  const valid = step !== 0 || selectedRoles.length > 0;
  const addField = (value: string, setValue: (value: string) => void, placeholder: string, action: () => void) => <div className="mt-4 flex gap-2"><input value={value} onChange={event => setValue(event.target.value)} onKeyDown={event => { if (event.key === "Enter") { event.preventDefault(); action(); } }} placeholder={placeholder} className="h-10 min-w-0 flex-1 rounded-xl border border-slate-700 bg-slate-900 px-3 text-sm text-white outline-none placeholder:text-slate-600 focus:border-violet-400" /><Button size="sm" variant="outline" onClick={action}><Plus size={14} />Add</Button></div>;
  let content: ReactNode;
  if (step === 0) content = <><h1>What kind of internship are you looking for?</h1><p>Select every role you&apos;d like to see. You can refine this any time.</p><div className="mt-7 flex flex-wrap gap-2">{roles.map(role => <OptionChip key={role} label={role} selected={selectedRoles.includes(role)} onClick={() => toggle(selectedRoles, setSelectedRoles, role)} />)}</div>{addField(roleInput, setRoleInput, "Add a custom role", addRole)}<div className="mt-5 flex flex-wrap gap-2">{selectedRoles.filter(role => !roles.includes(role)).map(role => <Badge key={role} className="border-violet-500/30 bg-violet-500/10 text-violet-200">{role}<button aria-label={`Remove ${role}`} className="ml-1.5" onClick={() => toggle(selectedRoles, setSelectedRoles, role)}><X size={13} /></button></Badge>)}</div></>;
  else if (step === 1) content = <><h1>Which skills should we prioritize?</h1><p>Choose the technologies you&apos;re comfortable representing on your applications.</p><div className="mt-7 flex flex-wrap gap-2">{skills.map(skill => <OptionChip key={skill} label={skill} selected={selectedSkills.includes(skill)} onClick={() => toggle(selectedSkills, setSelectedSkills, skill)} />)}</div>{addField(skillInput, setSkillInput, "Add another skill", addSkill)}</>;
  else if (step === 2) content = <><h1>Where would you like to work?</h1><p>Tell us about your preferred places and work arrangement.</p><div className="mt-7 grid gap-4 sm:grid-cols-2"><TextInput label="Preferred countries" value={countries} onChange={setCountries} placeholder="e.g. India, United States" /><TextInput label="Preferred cities" value={cities} onChange={setCities} placeholder="e.g. Bengaluru, London" /></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Toggle label="Remote roles" checked={workModes.remote} onChange={() => setWorkModes({ ...workModes, remote: !workModes.remote })} /><Toggle label="Hybrid roles" checked={workModes.hybrid} onChange={() => setWorkModes({ ...workModes, hybrid: !workModes.hybrid })} /><Toggle label="Onsite roles" checked={workModes.onsite} onChange={() => setWorkModes({ ...workModes, onsite: !workModes.onsite })} /><Toggle label="Willing to relocate" checked={workModes.relocate} onChange={() => setWorkModes({ ...workModes, relocate: !workModes.relocate })} /></div></>;
  else if (step === 3) content = <><h1>What internship duration works for you?</h1><p>Use a range to keep good opportunities from slipping through.</p><div className="mt-7 grid gap-4 sm:grid-cols-3"><TextInput label="Minimum" value={duration.min} onChange={value => setDuration({ ...duration, min: value })} type="number" /><TextInput label="Maximum" value={duration.max} onChange={value => setDuration({ ...duration, max: value })} type="number" /><label className="block text-sm font-medium text-slate-300">Unit<select value={duration.unit} onChange={event => setDuration({ ...duration, unit: event.target.value })} className="mt-2 h-11 w-full rounded-xl border border-slate-700 bg-slate-900 px-3 text-sm text-white outline-none focus:border-violet-400"><option value="weeks">Weeks</option><option value="months">Months</option></select></label></div></>;
  else if (step === 4) content = <><h1>What compensation are you looking for?</h1><p>We&apos;ll use this as a preference, not a hard exclusion unless you change it later.</p><div className="mt-7 grid gap-4 sm:grid-cols-3"><TextInput label="Minimum stipend" value={compensation.minimum} onChange={value => setCompensation({ ...compensation, minimum: value })} type="number" placeholder="0" /><label className="block text-sm font-medium text-slate-300">Currency<select value={compensation.currency} onChange={event => setCompensation({ ...compensation, currency: event.target.value })} className="mt-2 h-11 w-full rounded-xl border border-slate-700 bg-slate-900 px-3 text-sm text-white outline-none"><option>USD</option><option>INR</option><option>EUR</option><option>GBP</option></select></label><label className="block text-sm font-medium text-slate-300">Preference<select value={compensation.cadence} onChange={event => setCompensation({ ...compensation, cadence: event.target.value })} className="mt-2 h-11 w-full rounded-xl border border-slate-700 bg-slate-900 px-3 text-sm text-white outline-none"><option value="monthly">Monthly</option><option value="hourly">Hourly</option></select></label></div><div className="mt-5"><Toggle label="Include unpaid internships" detail="Keep unpaid opportunities in your recommendations." checked={compensation.unpaid} onChange={() => setCompensation({ ...compensation, unpaid: !compensation.unpaid })} /></div></>;
  else if (step === 5) content = <><h1>When are you available?</h1><p>We&apos;ll use your preferred start window to rank roles that fit your plans.</p><div className="mt-7 grid gap-4 sm:grid-cols-2"><TextInput label="Earliest start date" value={availability.earliest} onChange={value => setAvailability({ ...availability, earliest: value })} type="date" /><TextInput label="Latest start date" value={availability.latest} onChange={value => setAvailability({ ...availability, latest: value })} type="date" /></div></>;
  else if (step === 6) content = <><h1>Anything else we should know?</h1><p>These preferences help make recommendations more useful from day one.</p><div className="mt-7 grid gap-4 sm:grid-cols-2"><TextInput label="Preferred industries" value={preferences.industries} onChange={value => setPreferences({ ...preferences, industries: value })} placeholder="e.g. Fintech, developer tools" /><TextInput label="Preferred companies" value={preferences.companies} onChange={value => setPreferences({ ...preferences, companies: value })} placeholder="e.g. Vercel, Figma" /><TextInput label="Excluded companies" value={preferences.excludedCompanies} onChange={value => setPreferences({ ...preferences, excludedCompanies: value })} placeholder="Companies to skip" /><TextInput label="Excluded keywords" value={preferences.keywords} onChange={value => setPreferences({ ...preferences, keywords: value })} placeholder="e.g. unpaid, commission" /><TextInput label="Maximum applications per day" value={preferences.maximum} onChange={value => setPreferences({ ...preferences, maximum: value })} type="number" suffix="applications" /></div></>;
  else if (step === 7) content = <><h1>Upload your master resume</h1><p>Your master resume is the source of truth for any tailored materials. InternAgent will not invent experience or achievements.</p><label className="mt-7 flex cursor-pointer flex-col items-center rounded-2xl border border-dashed border-slate-700 bg-slate-900/40 p-10 text-center transition hover:border-violet-400 hover:bg-violet-500/[0.04]"><input type="file" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" className="sr-only" onChange={selectResume} /><span className="grid h-12 w-12 place-items-center rounded-2xl bg-violet-500/15 text-violet-300"><FileUp size={22} /></span><span className="mt-4 font-medium text-white">{resumeName || "Choose a PDF or DOCX"}</span><span className="mt-2 text-sm text-slate-500">Maximum 5 MB · Your filename is shown, never a raw storage URL.</span><span className="mt-5 rounded-xl border border-slate-700 px-3 py-2 text-sm text-slate-300">Browse files</span></label>{resumeError ? <p className="mt-3 flex items-center gap-2 text-sm text-rose-300"><CircleAlert size={15} />{resumeError}</p> : null}{resumeName ? <div className="mt-4 flex items-center gap-2 rounded-xl border border-emerald-500/20 bg-emerald-500/[0.06] p-3 text-sm text-emerald-100"><ShieldCheck size={17} className="text-emerald-400" />{resumeName} is ready to use in this mocked onboarding flow.</div> : null}</>;
  else content = <><h1>How would you like to manage applications?</h1><p>You&apos;re always in control. Automatic submission can only happen through an authorized integration.</p><div className="mt-7 space-y-3">{([{ id: "review", title: "Review Every Application", detail: "Approve each tailored application before anything happens." }, { id: "batch", title: "Batch Approval", detail: "Review a prepared group, then approve selected applications together." }, { id: "authorized-auto", title: "Auto-submit only where authorized integrations permit it", detail: "Only routes through verified, permitted integrations; everything else stays assisted." }] as { id: ApplicationMode; title: string; detail: string }[]).map(mode => <button key={mode.id} onClick={() => setApplicationMode(mode.id)} className={cn("flex w-full items-start gap-4 rounded-2xl border p-5 text-left transition", applicationMode === mode.id ? "border-violet-400 bg-violet-500/10" : "border-slate-800 bg-slate-900/40 hover:border-slate-700")}><span className={cn("mt-0.5 grid h-5 w-5 place-items-center rounded-full border", applicationMode === mode.id ? "border-violet-300 bg-violet-500 text-white" : "border-slate-600")} >{applicationMode === mode.id ? <Check size={13} /> : null}</span><span><span className="block font-medium text-white">{mode.title}</span><span className="mt-1 block text-sm leading-6 text-slate-400">{mode.detail}</span></span></button>)}</div></>;
  return <main className="min-h-screen bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-violet-950/35 via-[#0c0c11] to-[#09090b] px-5 py-8 sm:px-8"><div className="mx-auto max-w-5xl"><header className="flex items-center justify-between"><button onClick={() => router.push("/login")} className="flex items-center gap-2 text-lg font-semibold tracking-tight text-white"><span className="grid h-8 w-8 place-items-center rounded-xl bg-violet-500"><Sparkles size={16} /></span>InternAgent</button><span className="text-sm text-slate-500">Step {step + 1} of {steps.length}</span></header><div className="mt-10 grid gap-8 lg:grid-cols-[220px_1fr]"><aside className="hidden lg:block">{steps.map((label, index) => <div key={label} className="flex items-center gap-3 py-2.5 text-sm"><span className={cn("grid h-6 w-6 place-items-center rounded-full text-xs font-medium", index < step ? "bg-violet-500 text-white" : index === step ? "border border-violet-400 bg-violet-500/15 text-violet-200" : "bg-slate-800 text-slate-500")}>{index < step ? <Check size={13} /> : index + 1}</span><span className={index === step ? "text-white" : "text-slate-500"}>{label}</span></div>)}</aside><section className="rounded-3xl border border-slate-800/80 bg-[#101016]/90 p-6 shadow-2xl shadow-black/30 sm:p-10"><div className="mb-8 flex gap-1.5 lg:hidden">{steps.map((label, index) => <span key={label} className={cn("h-1 flex-1 rounded-full", index <= step ? "bg-violet-400" : "bg-slate-800")} />)}</div><div className="max-w-2xl [&>h1]:text-2xl [&>h1]:font-semibold [&>h1]:tracking-tight [&>h1]:text-white sm:[&>h1]:text-3xl [&>p]:mt-3 [&>p]:text-sm [&>p]:leading-6 [&>p]:text-slate-400">{content}</div><footer className="mt-10 flex items-center justify-between border-t border-slate-800 pt-6"><Button variant="ghost" onClick={() => setStep(value => Math.max(0, value - 1))} disabled={step === 0}><ArrowLeft size={16} />Back</Button><Button onClick={next} disabled={!valid}>{step === steps.length - 1 ? "Finish setup" : "Continue"}<ArrowRight size={16} /></Button></footer></section></div></div></main>;
}
